server:
  port: 8070
  servlet:
    session:
      cookie:
        name: GATEWAY-CLIENT
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: resource-server
          uri: http://172.17.0.1:8090
          predicates:
            Path=/resource/**
          filters:
            - TokenRelay
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8080
      client:
        registration:
          messaging-gateway-oidc:
            provider: gateway-client-provider
            client-id: relive-client
            client-secret: relive-client
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
            client-name: messaging-gateway-oidc
        provider:
          gateway-client-provider:
            issuer-uri: http://172.17.0.1:8080
            authorization-uri: http://172.17.0.1:8080/oauth2/authorize
            token-uri: http://172.17.0.1:8080/oauth2/token
            jwk-set-uri: http://172.17.0.1:8080/oauth2/jwks
            user-info-uri: http://172.17.0.1:8080/userinfo
            user-name-attribute: sub
logging:
  level:
#    root: INFO
#    org.springframework.web: INFO
    org.springframework.security: TRACE
#    org.springframework.security.oauth2: INFO
#    org.springframework.cloud.gateway: INFO
